```{r}
dx <- "rEQd6IDeXWT"
ou <- "BjC1xL40gHo"
pe <- "202109"

sample_df <- generate_url(dx, ou, pe)
```
```{r}

```



```{r}
sample_df %>% 
    transmute(
        data_element,
        period = my(period),
        organisation_unit,
        value
    )
```


```{r}
library(dhis2r)

dhis2_connection <- Dhis2r$new(
    base_url = "https://hiskenya.org/",
    username = "mikonya",
    password = "Kenya2030"
)


tryCatch(
    expr = {
        dhis2_connection$get_analytics(
        analytic = dx,
        org_unit = ou,
        period = pe,
        output_scheme = "NAME"
        )
    },
    error = function(e){
        print(e)
    }
)


library(httr)

url <- "https://hiskenya.org/api/me"
username<-"mikonya"
password<-"Kenya2030"
login<-GET(url, authenticate(username,password))
#If we cannot login, stop with an error
if(login$status == 200L) { print("Logged in successfully!")} else {stop("Could not login")}
```

```{r}
library(DBI)

my_db_connection <- dbConnect(drv = odbc::odbc(), .connection_string = "Driver={PostgreSQL ANSI(x64)};", 
    database = "FP", UID = Sys.getenv("POSTGRES_DB_NAME"), PWD = Sys.getenv("POSTGRES_DB_PASSWORD"), 
    Port = 5432, timeout = 10)

lite_conn <- sqlite_conn("metadata")

org_units <- dbGetQuery(my_db_connection, "select * from organisation_units")
dbWriteTable(lite_conn, "org_units", org_units)
data_elements <- dbGetQuery(my_db_connection, "select * from data_elements")
dbWriteTable(lite_conn, "data_elements", data_elements)
indicators <- dbGetQuery(my_db_connection, "select * from indicators")
dbWriteTable(lite_conn, "indicators", indicators)


```


```{r}
data_elements %>% 
    filter(
        name %in% c(focus_data_elements %>% pull(data_element))
    )

data_elements %>% 
    distinct(name)

```
```{r}
focus_data_elements
```


```{r}
data_elements <- function(){
    query_res <- dbGetQuery(
        lite_conn, 
        "SELECT name, id FROM data_elements WHERE name IN ('MOH 747A_DMPA-IM', 'MOH 747A_DMPA-SC');"
    ) 
    
    named_elements_vector <- set_names(query_res$id, query_res$id)
    return(named_elements_vector)
} 
    
```



```{r}
response <- dhis2_connection$get_analytics(
        analytic = dx,
        org_unit = ou,
        period = pe,
        output_scheme = "NAhME"
        )

class(response)

if (class(response) %in% c("tbl_df", "tbl", "data.frame")) {
    print("yes")
}
```
```{r}
library(gt)

# Function to apply custom styles to a gt table
style_gt_table <- function(gt_table, title = NULL, subtitle = NULL) {
  
  # Add title and subtitle if provided
  if (!is.null(title)) {
    gt_table <- gt_table %>%
      tab_header(
        title = title,
        subtitle = subtitle
      )
  }
  
  # Apply custom styles
  gt_table <- gt_table %>%
    tab_options(
      table.font.names = "Arial",
      table.font.size = px(14),
      table.border.top.style = "solid",
      table.border.top.width = px(3),
      table.border.bottom.style = "solid",
      table.border.bottom.width = px(3),
      heading.align = "center",
      heading.title.font.size = px(20),
      heading.subtitle.font.size = px(16),
      heading.title.font.weight = "bold"
    ) %>%
    tab_style(
      style = cell_borders(
        sides = "all",
        color = "grey",
        weight = px(1)
      ),
      locations = cells_body()
    ) %>%
    tab_style(
      style = cell_fill(color = "#f0f0f0"),
      locations = cells_column_labels()
    ) %>%
    tab_style(
      style = list(
        cell_text(weight = "bold", color = "#FFFFFF"),
        cell_fill(color = "#3c8dbc")
      ),
      locations = cells_column_labels()
    ) %>%
    tab_style(
      style = cell_text(align = "center"),
      locations = cells_body()
    )
  
  return(gt_table)
}

# Example usage with a sample dataset
data <- head(mtcars)
gt_table <- gt(data)

styled_table <- style_gt_table(
  gt_table,
  title = "Car Dataset",
  subtitle = "MTCars Sample Data"
)

styled_table

```
























